# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reuestId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('init', 'Initialize'), ('inprocess', 'In Process'), ('wait', 'Waiting'), ('succeeded', 'Completed'), ('failed', 'Failed')], max_length=20, verbose_name='current state of a process')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('init', 'Initialize'), ('inprocess', 'In Process'), ('wait', 'Waiting'), ('succeeded', 'Completed'), ('failed', 'Failed')], max_length=20, verbose_name='state of a process')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='widgets config, for internal use')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='widgets config, for internal use')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_gw.RequestSession')),
            ],
        ),
    ]
