# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 09:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_gw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='request_type',
            field=models.CharField(choices=[('vrt', 'Veris RunTime'), ('widget', 'Widget'), ('process', 'Process')], default=1, max_length=20, verbose_name='Request type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestsession',
            name='state',
            field=models.CharField(choices=[('init', 'Initialize'), ('inprocess', 'In Process'), ('wait', 'Waiting'), ('succeeded', 'Completed'), ('failed', 'Failed')], max_length=20, verbose_name='current state of a request'),
        ),
        migrations.AlterField(
            model_name='requesttrace',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='widgets config, for internal use'),
        ),
        migrations.AlterField(
            model_name='requesttrace',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='widgets config, for internal use'),
        ),
        migrations.AlterField(
            model_name='requesttrace',
            name='state',
            field=models.CharField(choices=[('init', 'Initialize'), ('inprocess', 'In Process'), ('wait', 'Waiting'), ('succeeded', 'Completed'), ('failed', 'Failed')], max_length=20, verbose_name='state of a request'),
        ),
    ]
