# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_gw', '0002_auto_20161221_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestsession',
            old_name='reuestId',
            new_name='requestId',
        ),
    ]
