# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_gw', '0003_auto_20161221_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttrace',
            name='parent_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vrt_session', to='process_gw.RequestSession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requesttrace',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_session', to='process_gw.RequestSession'),
        ),
    ]
