# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 09:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process_gw', '0004_auto_20161221_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestsession',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='requesttrace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requesttrace',
            name='parent_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vrt_session', to='process_gw.RequestSession', verbose_name='entire runtime session'),
        ),
        migrations.AlterField(
            model_name='requesttrace',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request payload'),
        ),
        migrations.AlterField(
            model_name='requesttrace',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_session', to='process_gw.RequestSession', verbose_name='individual request session id'),
        ),
        migrations.AlterField(
            model_name='requesttrace',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request Response'),
        ),
    ]
