# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process_gw', '0005_auto_20161222_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('runtime_type', models.CharField(max_length=64, unique=True)),
            ],
        )
    ]
