# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_gw', '0006_auto_20161223_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsession',
            name='runtime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='process_gw.Runtime'),
            preserve_default=False,
        ),
    ]
