# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 09:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VRT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='started at')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='ended at')),
                ('widgets_enabled', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='enabled widget for VRT')),
                ('vrt_type', models.CharField(choices=[('user', 'User Veris RunTime'), ('terminal', 'User Veris RunTime')], max_length=10, verbose_name='Type of VRT')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
