# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_extended', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrt',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ended at'),
        ),
    ]
