# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_extended', '0002_auto_20170106_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrt',
            name='widgets_enabled',
        ),
    ]
