# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_extended', '0003_remove_vrt_widgets_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrt',
            name='app_type',
            field=models.CharField(choices=[('vrt', 'Veris Run-Time'), ('widget', 'Widget'), ('process', 'Process'), ('resource', 'Rsource')], default=1, max_length=10, verbose_name='Type of Apps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vrt',
            name='vrt_type',
            field=models.CharField(choices=[('user', 'User Veris RunTime'), ('terminal', 'Terminal Veris RunTime')], max_length=10, verbose_name='Type of VRT'),
        ),
    ]
