# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminals',
            name='name',
            field=models.CharField(max_length=100, verbose_name='terminal name'),
        ),
        migrations.AlterField(
            model_name='terminals',
            name='widgets',
            field=models.ManyToManyField(to='widgets.Widgets', verbose_name='terminal associated widgets'),
        ),
    ]
