# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:50
from __future__ import unicode_literals

import apps.resource.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Resource Name')),
                ('host', models.CharField(max_length=50, verbose_name='Request HOST')),
                ('request_path', models.CharField(max_length=50, verbose_name='request path of API')),
                ('resource_end_point', models.URLField(editable=False, max_length=255, verbose_name='End Point used by Process')),
                ('actions', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'GET'), ('2', 'POSt'), ('3', 'PUT'), ('4', 'DELETE')], default=1, max_length=7, verbose_name='Resource allowed Methods')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
            ],
        ),
    ]
