# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 09:05
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20161229_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='actions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('get', 'GET'), ('post', 'POSt'), ('put', 'PUT'), ('delete', 'DELETE')], default=1, max_length=19, verbose_name='Resource allowed Methods'),
        ),
    ]
