# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20161229_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='sperated via comma , ', null=True, verbose_name='Keys for request Query params'),
        ),
        migrations.AddField(
            model_name='resource',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='sperated via comma , ', null=True, verbose_name='Keys for request post data'),
        ),
        migrations.AddField(
            model_name='resource',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='sperated via comma , ', null=True, verbose_name='Keys for request Headers'),
        ),
    ]
