# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20170102_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Resource Name')),
                ('upstream_url', models.CharField(max_length=50, verbose_name='Request HOST')),
                ('request_path', models.CharField(max_length=50, verbose_name='request path of API')),
                ('methods', multiselectfield.db.fields.MultiSelectField(choices=[('get', 'GET'), ('post', 'POSt'), ('put', 'PUT'), ('delete', 'DELETE')], default=1, max_length=19, verbose_name='Resource allowed Methods')),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='follow some standard rule, explained in respective models file', null=True, verbose_name='Define your headers here')),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='follow some standard rule, explained in respective models file', null=True, verbose_name='Define your Query params here')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='follow some standard rule, explained in respective models file', null=True, verbose_name='Define your Post data here')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resourceextended',
            unique_together=set([('upstream_url', 'request_path')]),
        ),
    ]
