# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20170102_1009'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='resource',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='resource.Resource'),
            preserve_default=False,
        ),
    ]
